//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expertia.Estructura.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ti-qa-webservices.webfarefinder.com/gnm/ws_compra.asmx")]
        public string Expertia_Estructura_ws_compra_ws_compra {
            get {
                return ((string)(this["Expertia_Estructura_ws_compra_ws_compra"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.webfarefinder.com/ws_pax_aux_test/ws_pax_paxdoc.asmx")]
        public string Expertia_Estructura_ws_pax_aux_ws_pax_paxdoc_ws_pax_paxdoc {
            get {
                return ((string)(this["Expertia_Estructura_ws_pax_aux_ws_pax_paxdoc_ws_pax_paxdoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ti-qa.webfarefinder.com/web_services/ws_crm.asmx")]
        public string Expertia_Estructura_ws_crm_ws_crm {
            get {
                return ((string)(this["Expertia_Estructura_ws_crm_ws_crm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webservices.webfarefinder.com/gnm/ws_pagoefectivo.asmx")]
        public string Expertia_Estructura_ws_pagoefectivo_ws_PagoEfectivo {
            get {
                return ((string)(this["Expertia_Estructura_ws_pagoefectivo_ws_PagoEfectivo"]));
            }
        }
    }
}
