//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Expertia.Estructura.ws_crm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws_crmSoap", Namespace="http://tempuri.org/")]
    public partial class ws_crm : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnvioDocumentosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws_crm() {
            this.Url = global::Expertia.Estructura.Properties.Settings.Default.Expertia_Estructura_ws_crm_ws_crm;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnvioDocumentosCompletedEventHandler EnvioDocumentosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioDocumentos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EnvioDocsRS EnvioDocumentos(EnvioDocsRQ EnvioDocsRQ) {
            object[] results = this.Invoke("EnvioDocumentos", new object[] {
                        EnvioDocsRQ});
            return ((EnvioDocsRS)(results[0]));
        }
        
        /// <remarks/>
        public void EnvioDocumentosAsync(EnvioDocsRQ EnvioDocsRQ) {
            this.EnvioDocumentosAsync(EnvioDocsRQ, null);
        }
        
        /// <remarks/>
        public void EnvioDocumentosAsync(EnvioDocsRQ EnvioDocsRQ, object userState) {
            if ((this.EnvioDocumentosOperationCompleted == null)) {
                this.EnvioDocumentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvioDocumentosOperationCompleted);
            }
            this.InvokeAsync("EnvioDocumentos", new object[] {
                        EnvioDocsRQ}, this.EnvioDocumentosOperationCompleted, userState);
        }
        
        private void OnEnvioDocumentosOperationCompleted(object arg) {
            if ((this.EnvioDocumentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnvioDocumentosCompleted(this, new EnvioDocumentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioDocsRQ {
        
        private int idReservaField;
        
        private int idCotizacionField;
        
        private string emailField;
        
        private string tokenField;
        
        private string formatoField;
        
        private string iPUsuarioField;
        
        private UsuarioSession usuario_SessionField;
        
        /// <remarks/>
        public int IdReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
            }
        }
        
        /// <remarks/>
        public int IdCotizacion {
            get {
                return this.idCotizacionField;
            }
            set {
                this.idCotizacionField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
            }
        }
        
        /// <remarks/>
        public string IPUsuario {
            get {
                return this.iPUsuarioField;
            }
            set {
                this.iPUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public UsuarioSession Usuario_Session {
            get {
                return this.usuario_SessionField;
            }
            set {
                this.usuario_SessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioSession {
        
        private string mensajeCambiarClaveField;
        
        private bool cambiarClaveField;
        
        private System.Nullable<System.DateTime> fecExpiraPassField;
        
        private System.Nullable<System.DateTime> fecUpdateField;
        
        private string autoLoginTrpField;
        
        private int idUsuarioField;
        
        private string nomUsuarioField;
        
        private string apePatUsuarioField;
        
        private string apeMatUsuarioField;
        
        private string emailUsuarioField;
        
        private string estadoUsuarioField;
        
        private string loginUsuarioField;
        
        private TIPO_USUARIO tipoUsuarioField;
        
        private string razonSocialCliEmpField;
        
        private int idCliEmpField;
        
        private int idDepField;
        
        private int idOfiField;
        
        private int idEmpField;
        
        private string nomCompletoField;
        
        private int idUsuWebSybaseField;
        
        private int idUsuETravelField;
        
        private string idVendedorPTAField;
        
        private bool esCounterAdminSRVField;
        
        private System.Nullable<int> idPlanillaField;
        
        private System.Nullable<int> idEmpresaPlanillaField;
        
        private bool esSupervisorSRVField;
        
        private string documentoField;
        
        private string clienteDkField;
        
        private string telfCasaUsuarioField;
        
        private string telfMovilUsuarioField;
        
        private string telfOficinaUsuarioField;
        
        /// <remarks/>
        public string MensajeCambiarClave {
            get {
                return this.mensajeCambiarClaveField;
            }
            set {
                this.mensajeCambiarClaveField = value;
            }
        }
        
        /// <remarks/>
        public bool CambiarClave {
            get {
                return this.cambiarClaveField;
            }
            set {
                this.cambiarClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FecExpiraPass {
            get {
                return this.fecExpiraPassField;
            }
            set {
                this.fecExpiraPassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FecUpdate {
            get {
                return this.fecUpdateField;
            }
            set {
                this.fecUpdateField = value;
            }
        }
        
        /// <remarks/>
        public string AutoLoginTrp {
            get {
                return this.autoLoginTrpField;
            }
            set {
                this.autoLoginTrpField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string NomUsuario {
            get {
                return this.nomUsuarioField;
            }
            set {
                this.nomUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string ApePatUsuario {
            get {
                return this.apePatUsuarioField;
            }
            set {
                this.apePatUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string ApeMatUsuario {
            get {
                return this.apeMatUsuarioField;
            }
            set {
                this.apeMatUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string EmailUsuario {
            get {
                return this.emailUsuarioField;
            }
            set {
                this.emailUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string EstadoUsuario {
            get {
                return this.estadoUsuarioField;
            }
            set {
                this.estadoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string LoginUsuario {
            get {
                return this.loginUsuarioField;
            }
            set {
                this.loginUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public TIPO_USUARIO TipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string RazonSocialCliEmp {
            get {
                return this.razonSocialCliEmpField;
            }
            set {
                this.razonSocialCliEmpField = value;
            }
        }
        
        /// <remarks/>
        public int IdCliEmp {
            get {
                return this.idCliEmpField;
            }
            set {
                this.idCliEmpField = value;
            }
        }
        
        /// <remarks/>
        public int IdDep {
            get {
                return this.idDepField;
            }
            set {
                this.idDepField = value;
            }
        }
        
        /// <remarks/>
        public int IdOfi {
            get {
                return this.idOfiField;
            }
            set {
                this.idOfiField = value;
            }
        }
        
        /// <remarks/>
        public int IdEmp {
            get {
                return this.idEmpField;
            }
            set {
                this.idEmpField = value;
            }
        }
        
        /// <remarks/>
        public string NomCompleto {
            get {
                return this.nomCompletoField;
            }
            set {
                this.nomCompletoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuWebSybase {
            get {
                return this.idUsuWebSybaseField;
            }
            set {
                this.idUsuWebSybaseField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuETravel {
            get {
                return this.idUsuETravelField;
            }
            set {
                this.idUsuETravelField = value;
            }
        }
        
        /// <remarks/>
        public string IdVendedorPTA {
            get {
                return this.idVendedorPTAField;
            }
            set {
                this.idVendedorPTAField = value;
            }
        }
        
        /// <remarks/>
        public bool EsCounterAdminSRV {
            get {
                return this.esCounterAdminSRVField;
            }
            set {
                this.esCounterAdminSRVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdPlanilla {
            get {
                return this.idPlanillaField;
            }
            set {
                this.idPlanillaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdEmpresaPlanilla {
            get {
                return this.idEmpresaPlanillaField;
            }
            set {
                this.idEmpresaPlanillaField = value;
            }
        }
        
        /// <remarks/>
        public bool EsSupervisorSRV {
            get {
                return this.esSupervisorSRVField;
            }
            set {
                this.esSupervisorSRVField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string ClienteDk {
            get {
                return this.clienteDkField;
            }
            set {
                this.clienteDkField = value;
            }
        }
        
        /// <remarks/>
        public string TelfCasaUsuario {
            get {
                return this.telfCasaUsuarioField;
            }
            set {
                this.telfCasaUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string TelfMovilUsuario {
            get {
                return this.telfMovilUsuarioField;
            }
            set {
                this.telfMovilUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string TelfOficinaUsuario {
            get {
                return this.telfOficinaUsuarioField;
            }
            set {
                this.telfOficinaUsuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TIPO_USUARIO {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        PERSONAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EnvioDocsRS {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void EnvioDocumentosCompletedEventHandler(object sender, EnvioDocumentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnvioDocumentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnvioDocumentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnvioDocsRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnvioDocsRS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591