//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Expertia.Estructura.ws_pagoefectivo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws_PagoEfectivoSoap", Namespace="http://tempuri.org/")]
    public partial class ws_PagoEfectivo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerarCIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesencriptarDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCIPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws_PagoEfectivo() {
            this.Url = global::Expertia.Estructura.Properties.Settings.Default.Expertia_Estructura_ws_pagoefectivo_ws_PagoEfectivo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerarCIPCompletedEventHandler GenerarCIPCompleted;
        
        /// <remarks/>
        public event DesencriptarDataCompletedEventHandler DesencriptarDataCompleted;
        
        /// <remarks/>
        public event ConsultarCIPCompletedEventHandler ConsultarCIPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarCIP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEpaymentResponse GenerarCIP(BEGenRequest objNMGenReq) {
            object[] results = this.Invoke("GenerarCIP", new object[] {
                        objNMGenReq});
            return ((BEpaymentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarCIPAsync(BEGenRequest objNMGenReq) {
            this.GenerarCIPAsync(objNMGenReq, null);
        }
        
        /// <remarks/>
        public void GenerarCIPAsync(BEGenRequest objNMGenReq, object userState) {
            if ((this.GenerarCIPOperationCompleted == null)) {
                this.GenerarCIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCIPOperationCompleted);
            }
            this.InvokeAsync("GenerarCIP", new object[] {
                        objNMGenReq}, this.GenerarCIPOperationCompleted, userState);
        }
        
        private void OnGenerarCIPOperationCompleted(object arg) {
            if ((this.GenerarCIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCIPCompleted(this, new GenerarCIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DesencriptarData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEnotificacionResponse DesencriptarData(string TextoEncriptado) {
            object[] results = this.Invoke("DesencriptarData", new object[] {
                        TextoEncriptado});
            return ((BEnotificacionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DesencriptarDataAsync(string TextoEncriptado) {
            this.DesencriptarDataAsync(TextoEncriptado, null);
        }
        
        /// <remarks/>
        public void DesencriptarDataAsync(string TextoEncriptado, object userState) {
            if ((this.DesencriptarDataOperationCompleted == null)) {
                this.DesencriptarDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesencriptarDataOperationCompleted);
            }
            this.InvokeAsync("DesencriptarData", new object[] {
                        TextoEncriptado}, this.DesencriptarDataOperationCompleted, userState);
        }
        
        private void OnDesencriptarDataOperationCompleted(object arg) {
            if ((this.DesencriptarDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesencriptarDataCompleted(this, new DesencriptarDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCIP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSConsultarCIPResponseMod1 ConsultarCIP(BEWSConsultarCIPRequestMod1 request) {
            object[] results = this.Invoke("ConsultarCIP", new object[] {
                        request});
            return ((BEWSConsultarCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCIPAsync(BEWSConsultarCIPRequestMod1 request) {
            this.ConsultarCIPAsync(request, null);
        }
        
        /// <remarks/>
        public void ConsultarCIPAsync(BEWSConsultarCIPRequestMod1 request, object userState) {
            if ((this.ConsultarCIPOperationCompleted == null)) {
                this.ConsultarCIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCIPOperationCompleted);
            }
            this.InvokeAsync("ConsultarCIP", new object[] {
                        request}, this.ConsultarCIPOperationCompleted, userState);
        }
        
        private void OnConsultarCIPOperationCompleted(object arg) {
            if ((this.ConsultarCIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCIPCompleted(this, new ConsultarCIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEGenRequest {
        
        private string idMonedaField;
        
        private string totalField;
        
        private string metodosPagoField;
        
        private string conceptoPagoField;
        
        private string codServicioField;
        
        private string codtransaccionField;
        
        private string emailComercioField;
        
        private string fechaAExpirarField;
        
        private string dataAdicionalField;
        
        private string usuarioIdField;
        
        private string usuarioNombreField;
        
        private string usuarioApellidosField;
        
        private string usuarioLocalidadField;
        
        private string usuarioProvinciaField;
        
        private string usuarioPaisField;
        
        private string usuarioAliasField;
        
        private string usuarioTipoDocField;
        
        private string usuarioNumeroDocField;
        
        private string usuarioEmailField;
        
        private Detalles detallesField;
        
        private int idDepartamentoField;
        
        private int idOficinaField;
        
        /// <remarks/>
        public string IdMoneda {
            get {
                return this.idMonedaField;
            }
            set {
                this.idMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string Total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string MetodosPago {
            get {
                return this.metodosPagoField;
            }
            set {
                this.metodosPagoField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptoPago {
            get {
                return this.conceptoPagoField;
            }
            set {
                this.conceptoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string CodServicio {
            get {
                return this.codServicioField;
            }
            set {
                this.codServicioField = value;
            }
        }
        
        /// <remarks/>
        public string Codtransaccion {
            get {
                return this.codtransaccionField;
            }
            set {
                this.codtransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string EmailComercio {
            get {
                return this.emailComercioField;
            }
            set {
                this.emailComercioField = value;
            }
        }
        
        /// <remarks/>
        public string FechaAExpirar {
            get {
                return this.fechaAExpirarField;
            }
            set {
                this.fechaAExpirarField = value;
            }
        }
        
        /// <remarks/>
        public string DataAdicional {
            get {
                return this.dataAdicionalField;
            }
            set {
                this.dataAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioNombre {
            get {
                return this.usuarioNombreField;
            }
            set {
                this.usuarioNombreField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioApellidos {
            get {
                return this.usuarioApellidosField;
            }
            set {
                this.usuarioApellidosField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioLocalidad {
            get {
                return this.usuarioLocalidadField;
            }
            set {
                this.usuarioLocalidadField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioProvincia {
            get {
                return this.usuarioProvinciaField;
            }
            set {
                this.usuarioProvinciaField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioPais {
            get {
                return this.usuarioPaisField;
            }
            set {
                this.usuarioPaisField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioAlias {
            get {
                return this.usuarioAliasField;
            }
            set {
                this.usuarioAliasField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioTipoDoc {
            get {
                return this.usuarioTipoDocField;
            }
            set {
                this.usuarioTipoDocField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioNumeroDoc {
            get {
                return this.usuarioNumeroDocField;
            }
            set {
                this.usuarioNumeroDocField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioEmail {
            get {
                return this.usuarioEmailField;
            }
            set {
                this.usuarioEmailField = value;
            }
        }
        
        /// <remarks/>
        public Detalles Detalles {
            get {
                return this.detallesField;
            }
            set {
                this.detallesField = value;
            }
        }
        
        /// <remarks/>
        public int IdDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                this.idDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        public int IdOficina {
            get {
                return this.idOficinaField;
            }
            set {
                this.idOficinaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Detalles {
        
        private Detalle detalleField;
        
        private string cod_OrigenField;
        
        private string tipoOrigenField;
        
        private string conceptoPagoField;
        
        private string importeField;
        
        /// <remarks/>
        public Detalle Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
        
        /// <remarks/>
        public string Cod_Origen {
            get {
                return this.cod_OrigenField;
            }
            set {
                this.cod_OrigenField = value;
            }
        }
        
        /// <remarks/>
        public string TipoOrigen {
            get {
                return this.tipoOrigenField;
            }
            set {
                this.tipoOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptoPago {
            get {
                return this.conceptoPagoField;
            }
            set {
                this.conceptoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Detalle {
        
        private string idDetalleOrdenPagoField;
        
        private string conceptoPagoField;
        
        private string importeField;
        
        private string tipo_OrigenField;
        
        private string cod_OrigenField;
        
        private string campo1Field;
        
        private string campo2Field;
        
        private string campo3Field;
        
        /// <remarks/>
        public string IdDetalleOrdenPago {
            get {
                return this.idDetalleOrdenPagoField;
            }
            set {
                this.idDetalleOrdenPagoField = value;
            }
        }
        
        /// <remarks/>
        public string ConceptoPago {
            get {
                return this.conceptoPagoField;
            }
            set {
                this.conceptoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string Importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_Origen {
            get {
                return this.tipo_OrigenField;
            }
            set {
                this.tipo_OrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Cod_Origen {
            get {
                return this.cod_OrigenField;
            }
            set {
                this.cod_OrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Campo1 {
            get {
                return this.campo1Field;
            }
            set {
                this.campo1Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo2 {
            get {
                return this.campo2Field;
            }
            set {
                this.campo2Field = value;
            }
        }
        
        /// <remarks/>
        public string Campo3 {
            get {
                return this.campo3Field;
            }
            set {
                this.campo3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPResponseMod1 {
        
        private string xMLField;
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <remarks/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPSField;
        
        private string infoRequestField;
        
        /// <remarks/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <remarks/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        public string CIPS {
            get {
                return this.cIPSField;
            }
            set {
                this.cIPSField = value;
            }
        }
        
        /// <remarks/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEnotificacionResponse {
        
        private string numeroCipField;
        
        private string idComercioField;
        
        private string estadoField;
        
        private string xmlField;
        
        /// <remarks/>
        public string NumeroCip {
            get {
                return this.numeroCipField;
            }
            set {
                this.numeroCipField = value;
            }
        }
        
        /// <remarks/>
        public string IdComercio {
            get {
                return this.idComercioField;
            }
            set {
                this.idComercioField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEpaymentResponse {
        
        private string numeroCipField;
        
        private string idComercioField;
        
        private string tokenField;
        
        private string estadoField;
        
        private string mensajeField;
        
        private string xmlField;
        
        /// <remarks/>
        public string NumeroCip {
            get {
                return this.numeroCipField;
            }
            set {
                this.numeroCipField = value;
            }
        }
        
        /// <remarks/>
        public string IdComercio {
            get {
                return this.idComercioField;
            }
            set {
                this.idComercioField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GenerarCIPCompletedEventHandler(object sender, GenerarCIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEpaymentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEpaymentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DesencriptarDataCompletedEventHandler(object sender, DesencriptarDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesencriptarDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesencriptarDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEnotificacionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEnotificacionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ConsultarCIPCompletedEventHandler(object sender, ConsultarCIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSConsultarCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSConsultarCIPResponseMod1)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591